# Generated by Django 3.2.7 on 2021-10-01 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=100, unique=True)),
                ('medicine_brand', models.CharField(choices=[('reckeweg', 'Reckeweg'), ('sbl', 'SBL'), ('schwabe', 'Schwabe'), ('bakson', 'Bakson'), ('bhargawa', 'Bhargawa')], max_length=100)),
                ('strength', models.CharField(choices=[('Mother', 'Mother'), ('CM', 'CM'), ('10M', '10M'), ('1M', '1M'), ('200', '200'), ('30', '30'), ('12', '12'), ('6x', '6X'), ('3x', '3X')], max_length=100, null=True)),
                ('in_stock', models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], max_length=100, null=True)),
                ('location', models.CharField(choices=[('r1-a', 'R1-A'), ('r1-b', 'R1-B'), ('r1-c', 'R1-C'), ('r1-d', 'R1-D'), ('r2-a', 'R2-A'), ('r2-b', 'R2-B'), ('r2-c', 'R2-C'), ('r2-d', 'R2-D')], max_length=6, null=True)),
                ('quantity', models.CharField(blank=True, default='', max_length=6, null=True)),
                ('count', models.IntegerField(blank=True, default=0, null=True)),
                ('date_of_mfg', models.DateField(blank=True, null=True)),
                ('date_of_exp', models.DateField(blank=True, null=True)),
                ('mrp', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('spr', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('therapeutic_use', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('symptom', models.CharField(blank=True, default='', max_length=500, null=True)),
            ],
        ),
    ]
