# Generated by Django 3.2.7 on 2021-09-19 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_code', models.CharField(max_length=100)),
                ('medicine_name', models.CharField(max_length=100)),
                ('medicine_brand', models.CharField(max_length=100)),
                ('date_of_mfg', models.DateTimeField()),
                ('date_of_exp', models.DateTimeField()),
            ],
        ),
    ]
