# Generated by Django 3.2.7 on 2021-09-19 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinedetails',
            name='date_of_exp',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='medicinedetails',
            name='date_of_mfg',
            field=models.DateField(),
        ),
    ]
