# Generated by Django 3.2.7 on 2021-10-01 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinedetail',
            name='symptom',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
