# Generated by Django 3.2.7 on 2021-10-01 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_medicinedetail_symptom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicinedetail',
            name='date_of_exp',
        ),
        migrations.RemoveField(
            model_name='medicinedetail',
            name='date_of_mfg',
        ),
        migrations.AlterField(
            model_name='medicinedetail',
            name='strength',
            field=models.CharField(choices=[('Combination', 'Combination'), ('ExternalUse', 'External Use'), ('Syrup', 'Syrup'), ('Mother', 'Mother'), ('CM', 'CM'), ('10M', '10M'), ('1M', '1M'), ('200', '200'), ('30', '30'), ('12', '12'), ('6x', '6X'), ('3x', '3X')], max_length=100, null=True),
        ),
    ]
