# Generated by Django 3.2.7 on 2021-09-19 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210919_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinedetails',
            name='date_of_exp',
            field=models.DateField(default=None),
        ),
    ]
