# Generated by Django 3.2.7 on 2021-10-04 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20211001_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinedetail',
            name='location',
            field=models.CharField(blank=True, choices=[('r1-a', 'R1-A'), ('r1-b', 'R1-B'), ('r1-c', 'R1-C'), ('r1-d', 'R1-D'), ('r2-a', 'R2-A'), ('r2-b', 'R2-B'), ('r2-c', 'R2-C'), ('r2-d', 'R2-D')], max_length=6, null=True),
        ),
    ]
