# Generated by Django 3.2.7 on 2021-10-09 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_patientdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdetail',
            name='clinic_info',
            field=models.CharField(blank=True, choices=[('pamplet', 'Newspaper'), ('online1', 'Practo'), ('online2', 'Google'), ('online3', 'Facebook'), ('online4', 'Instagram'), ('recommended', 'Recommended'), ('hoarding', 'Hoarding'), ('walk-in', 'WalkIn')], max_length=20, null=True),
        ),
    ]
