# Generated by Django 3.2.7 on 2021-09-19 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210919_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinedetail',
            name='symptom',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='medicinedetail',
            name='therapeutic_use',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
