# Generated by Django 3.2.7 on 2021-10-09 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_patientdetail_clinic_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdetail',
            name='patient_type',
            field=models.CharField(choices=[('new', 'New'), ('old', 'Old'), ('fup', 'FUP')], max_length=10),
        ),
    ]
