# Generated by Django 3.2.7 on 2021-09-19 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210919_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicinedetail',
            name='medicine_code',
        ),
        migrations.AlterField(
            model_name='medicinedetail',
            name='in_stock',
            field=models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='medicinedetail',
            name='medicine_brand',
            field=models.CharField(choices=[('reckeweg', 'Reckeweg'), ('sbl', 'SBL'), ('schwabe', 'Schwabe')], max_length=100),
        ),
        migrations.AlterField(
            model_name='medicinedetail',
            name='strength',
            field=models.CharField(choices=[('Mother', 'Mother'), ('CM', 'CM'), ('10M', '10M'), ('1M', '1M'), ('200', '200'), ('30', '30'), ('12', '12'), ('6x', '6X'), ('3x', '3X')], max_length=100, null=True),
        ),
    ]
