# Generated by Django 3.2.7 on 2021-09-29 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210919_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicinedetail',
            name='location',
            field=models.CharField(choices=[('r1-a', 'R1-A'), ('r1-b', 'R1-B'), ('r1-c', 'R1-C'), ('r1-d', 'R1-D'), ('r2-a', 'R2-A'), ('r2-b', 'R2-B'), ('r2-c', 'R2-C'), ('r2-d', 'R2-D')], default='', max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='medicinedetail',
            name='mrp',
            field=models.CharField(blank=True, default='', max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='medicinedetail',
            name='quantity',
            field=models.CharField(blank=True, default='', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='medicinedetail',
            name='spr',
            field=models.CharField(blank=True, default='', max_length=6, null=True),
        ),
    ]
