# Generated by Django 3.2.7 on 2021-10-12 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20211009_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdetail',
            name='advice',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='patientdetail',
            name='family_history',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='patientdetail',
            name='generalities',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='patientdetail',
            name='lab_reports',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='patientdetail',
            name='on_examination',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='patientdetail',
            name='past_history',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='medicinedetail',
            name='in_stock',
            field=models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='medicinedetail',
            name='strength',
            field=models.CharField(choices=[('Combination', 'Combination'), ('ExternalUse', 'External Use'), ('Syrup', 'Syrup'), ('Mother', 'Mother'), ('CM', 'CM'), ('10M', '10M'), ('1M', '1M'), ('200', '200'), ('30', '30'), ('12', '12'), ('6x', '6X'), ('3x', '3X')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='medicinedetail',
            name='therapeutic_use',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='patientdetail',
            name='disease',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='patientdetail',
            name='prescription',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='patientdetail',
            name='symptoms',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
