# Generated by Django 3.2.7 on 2021-09-29 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210929_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinedetail',
            name='mrp',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='medicinedetail',
            name='spr',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
