# Generated by Django 3.2.7 on 2021-10-15 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20211012_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinedetail',
            name='symptom',
            field=models.TextField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='medicinedetail',
            name='therapeutic_use',
            field=models.TextField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='patientdetail',
            name='advice',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='patientdetail',
            name='disease',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='patientdetail',
            name='family_history',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='patientdetail',
            name='generalities',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='patientdetail',
            name='lab_reports',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='patientdetail',
            name='on_examination',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='patientdetail',
            name='past_history',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='patientdetail',
            name='prescription',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='patientdetail',
            name='symptoms',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
