# Generated by Django 3.2.7 on 2021-10-22 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20211015_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdetail',
            name='symptoms',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
